<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>宏任务和微任务理解</title>
</head>

<body>
    <script type="text">
        // 1-执行整体script代码（宏任务队列）
        // 2-同步任务执行
        console.log('start')

        // 3-放入宏任务队列
        setTimeout(function () {
            // 微任务
            console.log('setTimeout')
        }, 0)

        // 放入微任务队列
        Promise.resolve().then(function () {
            console.log('promise1')
        }).then(function () {
            console.log('promise2')
        })

        // 同步任务
        console.log('end')

        // event-loop-1 整体代码载入之后执行微任务队列
        // event-loop-2 执行下一个宏任务 setTimeout
        // event-loop-3 检查微任务队列 => 执行微任务队列

        // start => end => promise1 => promise2 => setTimeout
    </script>

    <script type="text">
        // scrit 宏任务执行-同步任务执行
        console.log('start')

        // 1-推入宏任务队列
        // 5 - event-loop => 执行第二个宏任务，检查微任务队列
        setTimeout(() => {
            console.log('setTimeout1')
            // 添加至微任务队列
            // 6 - 执行第二个宏任务下的微任务
            Promise.resolve().then(() => {
                console.log('promise1');
            })
        }, 0)

        // 1 - 推入微任务队列
        // 2 - 执行微任务
        new Promise(function (resolve, reject) {
            console.log('promise2')
            // 3 - 添加到宏任务队列
            // 7 event-loop - 执行第三个宏任务
            setTimeout(() => {
                console.log('setTimeout2')
                // 7-添加到微任务队列
                resolve('setTimeout3')
            }, 0)
        }).then(res => {
            // 4 - 添加到宏任务队列
            // 8 - event-loop 执行最后一个宏任务
            console.log('promise3');
            setTimeout(() => {
                console.log(res);
            }, 0)
        })

        // error: start => promise2 => promise3 => setTimeout1 => promise1 => setTimeout2 => setTimeout3

        // right: start => promise2 => setTimeout1 => promise1 => setTimeout2 => promise3 => setTiomeout3
    </script>

    <script type="text">
        const p = function () {
            // 微任务队列
            return new Promise((resolve, reject) => {
                // 微任务队列
                const p1 = new Promise((resolve, reject) => {
                    // 宏任务队列
                    setTimeout(() => {
                        resolve(1)
                    }, 0)
                    resolve(2)
                })
                // 宏任务队列
                p1.then((res) => {
                    console.log(res);
                })
                console.log(3);
                resolve(4);
            })
        }

        // 宏任务队列
        p().then((res) => {
            console.log(res);
        })
        console.log('end');

        //  3 => end => 2 => 4
    </script>

    <script type="text">
        async function async1() {
            console.log('async1 start')
            // 微任务 阻塞中
            await async2()
            console.log('async1 end')
        }
        async function async2() {
            console.log('async2')
        }
        console.log('script start')
        // 宏任务1
        setTimeout(function () {
            console.log('setTimeout')
        }, 0)
        async1();
        // 微任务1
        new Promise(function (resolve) {
            console.log('promise1')
            resolve();
        }).then(function () {
            // 宏任务2
            console.log('promise2')
        })
        console.log('script end')

        // error: script start =>  async1 start =>  async2 => async1 end => promise1 => setTimeout => promise2
        // right: script start => async1 start => promise1 => script end => async2 => async1 end => promise2 => script start
    </script>

    <script type="text">
        let resolvePromise = new Promise(resolve => {
            let resolvedPromise = Promise.resolve()
            resolve(resolvedPromise);
            // 提示：resolve(resolvedPromise) 等同于：
            // Promise.resolve().then(() => resolvedPromise.then(resolve));
        })
        resolvePromise.then(() => {
            console.log('resolvePromise resolved')
        })
        let resolvedPromiseThen = Promise.resolve().then(res => {
            console.log('promise1')
        })
        resolvedPromiseThen
            .then(() => {
                console.log('promise2')
            })
            .then(() => {
                console.log('promise3')
            })

        
        // 
    </script>

    <script>
        console.log('script start');

        // 宏任务1(延迟2s)
        setTimeout(() => {
            console.log('Gopal');
        }, 1 * 2000);

        Promise.resolve()
            .then(function () {
                console.log('promise1');
            }).then(function () {
                // 微任务1
                console.log('promise2');
            });


        async function foo() {
            // 微任务2-阻塞
            await bar()
            console.log('async1 end')
        }
        foo()

        async function errorFunc() {
            try {
                // Tips:参考：https://zh.javascript.info/promise-error-handling：隐式 try…catch
                // Promise.reject()方法返回一个带有拒绝原因的Promise对象
                // Promise.reject('error!!!') === new Error('error!!!')
                // 微任务3-阻塞
                await Promise.reject('error!!!')
            } catch (e) {
                console.log(e)
            }
            console.log('async1');
            return Promise.resolve('async1 success')
        }
        errorFunc().then(res => console.log(res))

        function bar() {
            console.log('async2 end')
        }

        console.log('script end');

        // script start => promise1 => async1 => async1 success => script end => promise2 
        // => async2 end => async1 end => Gopal
    </script>
</body>

</html>